Q2. This data set contains details of a startups and the target variable is a continuous variable.
Dataset contains input features and predicting profit. Construct two clusters using K Means
Algorithm using independent variable (R&amp;D Spend , Marketing Spend , State ) to predict profit
based on given data using Jupyter notebook and Deploy model on local host using Flask

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('./SET 22-2.csv')

In [3]:
print(dataset)

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       

In [15]:
dataset['State'].replace(['New York','California','Florida'],[1,2,3],inplace=True)
print(dataset)

    R&D Spend  Administration  Marketing Spend  State     Profit
0   165349.20       136897.80        471784.10      1  192261.83
1   162597.70       151377.59        443898.53      2  191792.06
2   153441.51       101145.55        407934.54      3  191050.39
3   144372.41       118671.85        383199.62      1  182901.99
4   142107.34        91391.77        366168.42      3  166187.94
5   131876.90        99814.71        362861.36      1  156991.12
6   134615.46       147198.87        127716.82      2  156122.51
7   130298.13       145530.06        323876.68      3  155752.60
8   120542.52       148718.95        311613.29      1  152211.77
9   123334.88       108679.17        304981.62      2  149759.96
10  101913.08       110594.11        229160.95      3  146121.95
11  100671.96        91790.61        249744.55      2  144259.40
12   93863.75       127320.38        249839.44      3  141585.52
13   91992.39       135495.07        252664.93      2  134307.35
14  119943.24       15654

In [16]:
dataset.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [17]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     int64  
 4   Profit           50 non-null     float64
dtypes: float64(4), int64(1)
memory usage: 2.1 KB


In [18]:
X = dataset.iloc[:,[0,2,3]].values
Y = dataset.iloc[:,4].values

In [19]:
print(X)

[[1.6534920e+05 4.7178410e+05 1.0000000e+00]
 [1.6259770e+05 4.4389853e+05 2.0000000e+00]
 [1.5344151e+05 4.0793454e+05 3.0000000e+00]
 [1.4437241e+05 3.8319962e+05 1.0000000e+00]
 [1.4210734e+05 3.6616842e+05 3.0000000e+00]
 [1.3187690e+05 3.6286136e+05 1.0000000e+00]
 [1.3461546e+05 1.2771682e+05 2.0000000e+00]
 [1.3029813e+05 3.2387668e+05 3.0000000e+00]
 [1.2054252e+05 3.1161329e+05 1.0000000e+00]
 [1.2333488e+05 3.0498162e+05 2.0000000e+00]
 [1.0191308e+05 2.2916095e+05 3.0000000e+00]
 [1.0067196e+05 2.4974455e+05 2.0000000e+00]
 [9.3863750e+04 2.4983944e+05 3.0000000e+00]
 [9.1992390e+04 2.5266493e+05 2.0000000e+00]
 [1.1994324e+05 2.5651292e+05 3.0000000e+00]
 [1.1452361e+05 2.6177623e+05 1.0000000e+00]
 [7.8013110e+04 2.6434606e+05 2.0000000e+00]
 [9.4657160e+04 2.8257431e+05 1.0000000e+00]
 [9.1749160e+04 2.9491957e+05 3.0000000e+00]
 [8.6419700e+04 0.0000000e+00 1.0000000e+00]
 [7.6253860e+04 2.9866447e+05 2.0000000e+00]
 [7.8389470e+04 2.9973729e+05 1.0000000e+00]
 [7.399456

In [20]:
print(Y)

[192261.83 191792.06 191050.39 182901.99 166187.94 156991.12 156122.51
 155752.6  152211.77 149759.96 146121.95 144259.4  141585.52 134307.35
 132602.65 129917.04 126992.93 125370.37 124266.9  122776.86 118474.03
 111313.02 110352.25 108733.99 108552.04 107404.34 105733.54 105008.31
 103282.38 101004.64  99937.59  97483.56  97427.84  96778.92  96712.8
  96479.51  90708.19  89949.14  81229.06  81005.76  78239.91  77798.83
  71498.49  69758.98  65200.33  64926.08  49490.75  42559.73  35673.41
  14681.4 ]


In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y, test_size=0.25,random_state=42)

In [22]:
print(X_train)

[[1.2054252e+05 3.1161329e+05 1.0000000e+00]
 [1.4437241e+05 3.8319962e+05 1.0000000e+00]
 [1.3461546e+05 1.2771682e+05 2.0000000e+00]
 [2.7892920e+04 1.6447071e+05 3.0000000e+00]
 [1.3154600e+03 2.9711446e+05 3.0000000e+00]
 [0.0000000e+00 0.0000000e+00 2.0000000e+00]
 [1.1452361e+05 2.6177623e+05 1.0000000e+00]
 [1.2333488e+05 3.0498162e+05 2.0000000e+00]
 [7.8013110e+04 2.6434606e+05 2.0000000e+00]
 [7.7044010e+04 1.4057481e+05 1.0000000e+00]
 [4.6426070e+04 2.1079767e+05 2.0000000e+00]
 [6.1136380e+04 8.8218230e+04 1.0000000e+00]
 [1.6534920e+05 4.7178410e+05 1.0000000e+00]
 [2.2177740e+04 2.8334720e+04 2.0000000e+00]
 [7.2107600e+04 3.5318381e+05 1.0000000e+00]
 [5.5493950e+04 2.1463481e+05 3.0000000e+00]
 [1.3187690e+05 3.6286136e+05 1.0000000e+00]
 [6.5605480e+04 1.0713838e+05 1.0000000e+00]
 [1.0067196e+05 2.4974455e+05 2.0000000e+00]
 [2.8663760e+04 2.0112682e+05 3.0000000e+00]
 [1.6259770e+05 4.4389853e+05 2.0000000e+00]
 [7.8389470e+04 2.9973729e+05 1.0000000e+00]
 [1.534415

In [23]:
print(X_test)

[[9.1992390e+04 2.5266493e+05 2.0000000e+00]
 [3.8558510e+04 1.7499930e+05 2.0000000e+00]
 [6.1994480e+04 9.1131240e+04 3.0000000e+00]
 [1.0002300e+03 1.9039300e+03 1.0000000e+00]
 [9.4657160e+04 2.8257431e+05 1.0000000e+00]
 [5.4205000e+02 0.0000000e+00 1.0000000e+00]
 [7.5328870e+04 1.3405007e+05 3.0000000e+00]
 [6.4664710e+04 1.3796262e+05 2.0000000e+00]
 [6.3408860e+04 4.6085250e+04 2.0000000e+00]
 [8.6419700e+04 0.0000000e+00 1.0000000e+00]
 [9.3863750e+04 2.4983944e+05 3.0000000e+00]
 [1.4210734e+05 3.6616842e+05 3.0000000e+00]
 [4.4069950e+04 1.9702942e+05 2.0000000e+00]]


In [24]:
print(Y_train)

[152211.77 182901.99 156122.51  77798.83  49490.75  42559.73 129917.04
 149759.96 126992.93 108552.04  96712.8   97483.56 192261.83  65200.33
 105008.31  96778.92 156991.12 101004.64 144259.4   90708.19 191792.06
 111313.02 191050.39  69758.98  96479.51 108733.99  78239.91 146121.95
 110352.25 124266.9   14681.4  118474.03 155752.6   71498.49 132602.65
 103282.38  81229.06]


In [25]:
print(Y_test)

[134307.35  81005.76  99937.59  64926.08 125370.37  35673.41 105733.54
 107404.34  97427.84 122776.86 141585.52 166187.94  89949.14]


In [26]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(X_train) 
x_test = sc.fit_transform(X_test)

# Construct two clusters using K Means 
Algorithm using independent variable

In [27]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=2,init='k-means++',random_state=42)
print(kmeans)
y_means = kmeans.fit_predict(X)

KMeans(n_clusters=2, random_state=42)


C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


In [28]:
print(y_means)

[1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0]


In [29]:
import pickle
print("[INFO] Saving model...")
saved_model=pickle.dump(kmeans,open('kmeanscluster.pkl', 'wb'))

[INFO] Saving model...


In [30]:
model = pickle.load(open('kmeanscluster.pkl','rb'))
model.predict(X)

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0])

from flask import Flask, render_template,request

import pickle

model = pickle.load(open('kmeanscluster.pkl','rb'))
app = Flask(__name__,template_folder='Template')

@app.route('/')
def home():

    return render_template("index.html")
@app.route('/predict',methods=['POST'])
def predict():
    income = int(request.form.get('income'))
    score = int(request.form.get('score'))
    predict = model.predict([[income,score ]])
    if predict==[0]:
        result="Customer is careless"

    elif predict==[1]:
        result="Customer is standard"
    elif predict==[2]:
        result="Customer is Target"
    elif predict==[3]:
        result="Customer is careful"

    else:
        result="Custmor is sensible"
    return render_template('index.html', prediction_text='Model  has predicted  : {}'.format(result))
if __name__ == '__main__':
 app.run()