Q1.This data set contains details of a houses and the target variable is a continuous variable.
Dataset contains input features and predicting house prices. Apply necessary data preprocessing -
Construct Linear Regression Model using dependent variable to predict house prices based on
given data using Jupyter Notebook. Use Area, bathrooms, stories, main road, guestroom,
hotwater heating, parking, prefarea, furnishing status.

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
dataset = pd.read_csv("./SET 21-1.csv")
print(dataset)

        price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating aircond

In [9]:
dataset.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [11]:
dataset['mainroad'].replace(['yes','no'],[1,0],inplace=True)
print(dataset)

        price  area  bedrooms  bathrooms  stories  mainroad guestroom  \
0    13300000  7420         4          2        3         1        no   
1    12250000  8960         4          4        4         1        no   
2    12250000  9960         3          2        2         1        no   
3    12215000  7500         4          2        2         1        no   
4    11410000  7420         4          1        2         1       yes   
..        ...   ...       ...        ...      ...       ...       ...   
540   1820000  3000         2          1        1         1        no   
541   1767150  2400         3          1        1         0        no   
542   1750000  3620         2          1        1         1        no   
543   1750000  2910         3          1        1         0        no   
544   1750000  3850         3          1        2         1        no   

    basement hotwaterheating airconditioning  parking prefarea  \
0         no              no             yes        2    

In [12]:
dataset['guestroom'].replace(['yes','no'],[1,0],inplace=True)
print(dataset)

        price  area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0    13300000  7420         4          2        3         1          0   
1    12250000  8960         4          4        4         1          0   
2    12250000  9960         3          2        2         1          0   
3    12215000  7500         4          2        2         1          0   
4    11410000  7420         4          1        2         1          1   
..        ...   ...       ...        ...      ...       ...        ...   
540   1820000  3000         2          1        1         1          0   
541   1767150  2400         3          1        1         0          0   
542   1750000  3620         2          1        1         1          0   
543   1750000  2910         3          1        1         0          0   
544   1750000  3850         3          1        2         1          0   

    basement hotwaterheating airconditioning  parking prefarea  \
0         no              no             yes 

In [13]:
dataset['hotwaterheating'].replace(['yes','no'],[1,0],inplace=True)
print(dataset)

        price  area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0    13300000  7420         4          2        3         1          0   
1    12250000  8960         4          4        4         1          0   
2    12250000  9960         3          2        2         1          0   
3    12215000  7500         4          2        2         1          0   
4    11410000  7420         4          1        2         1          1   
..        ...   ...       ...        ...      ...       ...        ...   
540   1820000  3000         2          1        1         1          0   
541   1767150  2400         3          1        1         0          0   
542   1750000  3620         2          1        1         1          0   
543   1750000  2910         3          1        1         0          0   
544   1750000  3850         3          1        2         1          0   

    basement  hotwaterheating airconditioning  parking prefarea  \
0         no                0             ye

In [14]:
dataset['prefarea'].replace(['yes','no'],[1,0],inplace=True)
print(dataset)

        price  area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0    13300000  7420         4          2        3         1          0   
1    12250000  8960         4          4        4         1          0   
2    12250000  9960         3          2        2         1          0   
3    12215000  7500         4          2        2         1          0   
4    11410000  7420         4          1        2         1          1   
..        ...   ...       ...        ...      ...       ...        ...   
540   1820000  3000         2          1        1         1          0   
541   1767150  2400         3          1        1         0          0   
542   1750000  3620         2          1        1         1          0   
543   1750000  2910         3          1        1         0          0   
544   1750000  3850         3          1        2         1          0   

    basement  hotwaterheating airconditioning  parking  prefarea  \
0         no                0             y

In [15]:
dataset['furnishingstatus'].replace(['furnished','semi-furnished','unfurnished'],[2,1,0],inplace=True)
print(dataset)

        price  area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0    13300000  7420         4          2        3         1          0   
1    12250000  8960         4          4        4         1          0   
2    12250000  9960         3          2        2         1          0   
3    12215000  7500         4          2        2         1          0   
4    11410000  7420         4          1        2         1          1   
..        ...   ...       ...        ...      ...       ...        ...   
540   1820000  3000         2          1        1         1          0   
541   1767150  2400         3          1        1         0          0   
542   1750000  3620         2          1        1         1          0   
543   1750000  2910         3          1        1         0          0   
544   1750000  3850         3          1        2         1          0   

    basement  hotwaterheating airconditioning  parking  prefarea  \
0         no                0             y

In [10]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   price             545 non-null    int64 
 1   area              545 non-null    int64 
 2   bedrooms          545 non-null    int64 
 3   bathrooms         545 non-null    int64 
 4   stories           545 non-null    int64 
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64 
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB


Area, bathrooms, stories, main road, guestroom,
hotwater heating, parking, prefarea, furnishing status.

In [16]:
X = dataset.iloc[:,[1,3,4,5,6,8,10,11,12]].values
Y = dataset.iloc[:,0].values

In [17]:
print(X)

[[7420    2    3 ...    2    1    2]
 [8960    4    4 ...    3    0    2]
 [9960    2    2 ...    2    1    1]
 ...
 [3620    1    1 ...    0    0    0]
 [2910    1    1 ...    0    0    2]
 [3850    1    2 ...    0    0    0]]


In [18]:
print(Y)

[13300000 12250000 12250000 12215000 11410000 10850000 10150000 10150000
  9870000  9800000  9800000  9681000  9310000  9240000  9240000  9100000
  9100000  8960000  8890000  8855000  8750000  8680000  8645000  8645000
  8575000  8540000  8463000  8400000  8400000  8400000  8400000  8400000
  8295000  8190000  8120000  8080940  8043000  7980000  7962500  7910000
  7875000  7840000  7700000  7700000  7560000  7560000  7525000  7490000
  7455000  7420000  7420000  7420000  7350000  7350000  7350000  7350000
  7343000  7245000  7210000  7210000  7140000  7070000  7070000  7035000
  7000000  6930000  6930000  6895000  6860000  6790000  6790000  6755000
  6720000  6685000  6650000  6650000  6650000  6650000  6650000  6650000
  6629000  6615000  6615000  6580000  6510000  6510000  6510000  6475000
  6475000  6440000  6440000  6419000  6405000  6300000  6300000  6300000
  6300000  6300000  6293000  6265000  6230000  6230000  6195000  6195000
  6195000  6160000  6160000  6125000  6107500  6090

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y, test_size=0.25,random_state=42)

In [20]:
print(X_train)

[[4600    2    1 ...    2    0    1]
 [5640    1    1 ...    0    0    1]
 [3520    1    2 ...    0    1    1]
 ...
 [4500    2    3 ...    1    0    2]
 [4040    1    1 ...    0    0    0]
 [5500    2    4 ...    1    0    1]]


In [21]:
print(Y_train)

[ 5285000  3675000  4200000  2275000  3570000  4620000  4200000  3087000
  3255000  8855000  3640000  7343000  4690000  4305000  3640000  4403000
  4270000  2940000  4795000  8540000  4235000  7700000  3500000  3360000
  4970000  3150000  5530000  5880000  3710000  3640000  8400000  6083000
  4760000  3080000  5243000  7245000  4550000  8575000  8960000  3500000
  6930000  4613000  4340000  4473000  3780000  6300000  5215000  5040000
  4515000  8645000  2660000  3118850  2450000 10850000  6020000  7560000
  4123000  4098500  9100000  7455000  4900000  3423000 12215000  4382000
  3850000  7140000  4970000  2380000  6090000  3710000  4200000  8400000
  4620000  4900000  8463000 10150000  5215000  7420000  6107500  7980000
  5495000  2450000  5950000  3465000  6020000  2450000  4900000  5250000
  3605000  4690000  5600000  5005000  3360000  3290000  4543000  4200000
  3395000  2653000  5652500  3395000  6895000  4270000  4690000  5250000
  5075000  3990000  3325000  2695000  5033000  6615

In [22]:
print(X_test)

[[5900    2    2 ...    1    0    0]
 [6500    2    3 ...    0    1    2]
 [4040    1    1 ...    0    0    1]
 ...
 [3650    1    2 ...    0    0    0]
 [3635    1    1 ...    0    0    0]
 [4000    1    1 ...    0    0    1]]


In [23]:
print(Y_test)

[ 4060000  6650000  3710000  6440000  2800000  4900000  5250000  4543000
  2450000  3353000 10150000  2660000  3360000  3360000  2275000  2660000
  2660000  7350000  2940000  2870000  6720000  5425000  1890000  5250000
  4193000 12250000  3080000  5110000  9800000  2520000  6790000  3500000
  6650000  2940000  3325000  4200000  4900000  3290000  3500000  2380000
  5495000  3675000  6650000  4907000  3150000  4480000  6580000  5740000
  3003000  1820000  8400000  2450000  4270000  4007500  3234000  1750000
  9800000  2100000  4340000  3045000  3850000  3500000  4753000  3080000
  4550000  6510000  6685000  5110000  4550000  6650000  3640000  5600000
  3780000  6615000  3220000  6650000  4690000  4830000  6860000  2233000
  7035000  4165000  6195000  6510000  1890000  8190000  2660000  4193000
 13300000  9681000  4340000  8645000  3703000  5145000  6440000  5950000
  5810000  5740000  6230000  5600000  3010000  8890000  4900000  5530000
  9100000  3773000  7910000  7350000  5530000  7525

In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(X_train)
x_test = sc.fit_transform(X_test)

In [26]:
print(x_train)

[[-0.25361539  1.5277588  -0.92057131 ...  1.56028336 -0.56225353
   0.06886505]
 [ 0.21717445 -0.55694217 -0.92057131 ... -0.82396987 -0.56225353
   0.06886505]
 [-0.74251253 -0.55694217  0.24586687 ... -0.82396987  1.77855709
   0.06886505]
 ...
 [-0.29888364  1.5277588   1.41230505 ...  0.36815675 -0.56225353
   1.40681449]
 [-0.50711761 -0.55694217 -0.92057131 ... -0.82396987 -0.56225353
  -1.2690844 ]
 [ 0.15379889  1.5277588   2.57874323 ...  0.36815675 -0.56225353
   0.06886505]]


In [27]:
print(x_test)

[[ 0.35378049  1.17429048  0.163605   ...  0.32421452 -0.52950338
  -1.09985336]
 [ 0.64315853  1.17429048  1.28429923 ... -0.75913645  1.88856206
   1.41147848]
 [-0.54329142 -0.61324058 -0.95708924 ... -0.75913645 -0.52950338
   0.15581256]
 ...
 [-0.73138715 -0.61324058  0.163605   ... -0.75913645 -0.52950338
  -1.09985336]
 [-0.7386216  -0.61324058 -0.95708924 ... -0.75913645 -0.52950338
  -1.09985336]
 [-0.56258329 -0.61324058 -0.95708924 ... -0.75913645 -0.52950338
   0.15581256]]


In [28]:
from sklearn.linear_model import LinearRegression
regression = LinearRegression()
regression.fit(X_train,Y_train)

LinearRegression()

In [29]:
Y_pred = regression.predict(X_test)
print(Y_pred)

[5024088.17644776 6919530.54631147 3310385.45238972 4018601.26198219
 3542959.03208864 3796874.88193105 5370066.67137883 6642151.58485472
 3358946.47408407 2853062.6051143  9318495.36672832 3026371.21126054
 2625759.36415746 3151704.70965641 3479043.08987686 5765961.95528695
 3188913.1743973  4323456.23555655 4281971.8311773  3852448.33627852
 5373820.5465998  5382514.2741616  2947550.84293998 5016920.01845819
 5323687.02120891 7745005.00322071 3375898.62681294 5372836.43715245
 7826051.09251419 3720174.46562678 5530709.58972424 3526955.67147504
 6645240.14630266 4465250.01579873 3701676.06004548 5260682.69738417
 5069626.14466793 3260558.56014617 2559384.31715067 4730982.25207431
 4966024.2202457  2942296.1517186  6897405.53064254 4335040.57374131
 4059870.35817475 3848935.90396716 6250310.84164049 4202029.56455258
 4164703.26742702 3334043.39948692 7294761.69916297 3051052.52640635
 4879653.77640203 3538892.48386269 3387777.40024252 2911140.77124524
 7511364.15918504 3044839.6573741 

In [35]:
from sklearn.metrics import mean_squared_error, r2_score

In [36]:
mse = mean_squared_error(Y_test, Y_pred)
r2 = r2_score(Y_test, Y_pred)

print(f"Mean Squared Error: {mse:.2f}")
print(f"R-Squared: {r2:.2f}")

Mean Squared Error: 1762440300365.03
R-Squared: 0.62


In [43]:
prediction = regression.predict(X_test)[0]
print(f"Predicted price: {prediction:.2f}")

Predicted price: 5024088.18


In [44]:
import pickle
print("[Info] Saving Model")
saved_model = pickle.dump(regression,open('model1.pkl','wb'))

[Info] Saving Model


In [45]:
model = pickle.load(open('model1.pkl','rb'))
model.predict(X_test)

array([5024088.17644776, 6919530.54631147, 3310385.45238972,
       4018601.26198219, 3542959.03208864, 3796874.88193105,
       5370066.67137883, 6642151.58485472, 3358946.47408407,
       2853062.6051143 , 9318495.36672832, 3026371.21126054,
       2625759.36415746, 3151704.70965641, 3479043.08987686,
       5765961.95528695, 3188913.1743973 , 4323456.23555655,
       4281971.8311773 , 3852448.33627852, 5373820.5465998 ,
       5382514.2741616 , 2947550.84293998, 5016920.01845819,
       5323687.02120891, 7745005.00322071, 3375898.62681294,
       5372836.43715245, 7826051.09251419, 3720174.46562678,
       5530709.58972424, 3526955.67147504, 6645240.14630266,
       4465250.01579873, 3701676.06004548, 5260682.69738417,
       5069626.14466793, 3260558.56014617, 2559384.31715067,
       4730982.25207431, 4966024.2202457 , 2942296.1517186 ,
       6897405.53064254, 4335040.57374131, 4059870.35817475,
       3848935.90396716, 6250310.84164049, 4202029.56455258,
       4164703.26742702,